extends: conditional
message: Use the full product name (Couchbase Autonomous Operator) first.
level: error
scope: text
ignorecase: false
first: Operator 
second: (Couchbase Autonomous Operator|Couchbase Autonomous Operator for Kubernetes)